### ISSUE TITLE
Cannot Resolve AppviralityInstallReferrerReceiver

### ISSUE THREAD

**Issue by stripathi669** [appvirality/appvirality-sdk-android#3]
Hi 
I was following the tutorial and I'm using gradle for that.
I have added the lib to build.gradle and built successfully.

However, I cannot resolve `AppviralityInstallReferrerReceiver` class, or import package `com.appvirality.android` for that matter.

**Comment by RamPapineni** [comment]
Please have a look at sample project and make sure that your App uses the jcenter repository.
